name = "splines"
version = "0.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "Popular parametric splines for Gleam"
licences = ["MIT"]
repository = { type = "github", user = "seancribbs", repo = "splines" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
vec = ">= 3.0.3 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
